database:
  connection_string: "file:catbox-found-ids.sqlite"

master_server:
  enabled: false
  endpoint: "http://localhost:6969/add"
  auth_key: "omgwow"

scanner:
  num_workers: 1000
  request_timeout: 5s
  exts:
    - "mp4"
    # - "mkv"
    # - "webm"

    - "png"
    - "jpg"
    # - "gif"

    - "zip"
    # - "rar"
    # - "7z"

    - "pdf"
    # - "csv"
    # - "xlsx"
