database:
  connection_string: "file:catbox.db"

scanner:
  num_workers: 1000
  request_timeout: 5s
  exts:
    - "mp4"
    # - "mkv"
    # - "webm"

    - "png"
    - "jpg"
    # - "gif"

    - "zip"
    # - "rar"
    # - "7z"

    - "pdf"
    # - "csv"
    # - "xlsx"
